apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-sample
  name: php-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-sample
  template:
    metadata:
      labels:
        app: php-sample
    spec:
      containers:
        - image: quay.io/helloworld/php-sample:latest
          imagePullPolicy: Always
          name: php-sample
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
         
